### ISSUE TITLE
Warning Message: Script not found

### ISSUE THREAD

**Issue by SAYREXx** [HyunsukBaek/AOSOUL#4]
16:11:05 Warning Message: Script core\vAH\fn_vAH_load.sqf not found
16:11:05 Warning Message: Script core\vAH\fn_vAH_buy.sqf not found
16:11:05 Warning Message: Script core\vAH\fn_vAH_reciever.sqf not found
16:11:05 Warning Message: Script core\vAH\fn_vAH_loadInventory.sqf not found
16:11:05 Warning Message: Script core\vAH\fn_vAH_sell.sqf not found
16:11:05 Warning Message: Script core\vAH\fn_vAH_checkItem.sqf not found
16:11:05 Warning Message: Script core\vAH\fn_vAH_takeBack.sqf not found
16:11:05 Warning Message: Script core\vAH\fn_vAH_select.sqf not found

**Comment by SAYREXx** [comment]
Decided error. Thank you!

**Comment by HyunsukBaek** [comment]
We deleted Auction House cause by internel errors and not used by users.

**Comment by HyunsukBaek** [comment]
@SAYREXx  do you play altislife mod on your server?

**Comment by SAYREXx** [comment]
yes
